name: instant_sos
description: Instant SOS Emergency Alert App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # مكتبات إدارة الحالة والحفظ المحلي لاسم المستخدم
  shared_preferences: ^2.2.2
  
  # مكتبة خدمات الوصول لمراقبة الأزرار
  flutter_accessibility_service: ^0.5.0
  
  # مكتبات الاتصال الفوري والبث اللحظي
  pusher_channels_flutter: ^2.2.0
  http: ^1.1.2
  crypto: ^3.0.3
  
  # مكتبات جلب بيانات الطوارئ (الموقع والبطارية)
  geolocator: ^10.1.0      # لجلب الإحداثيات الجغرافية
  battery_plus: ^5.0.3     # لمعرفة نسبة شحن البطارية الحالية

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
